### ISSUE TITLE
Array Deque crash on client

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#184]
```
java.util.NoSuchElementException
	at java.base/java.util.ArrayDeque.getLast(ArrayDeque.java:413)
	at net.minecraft.class_4587.method_22903(class_4587.java:62)
	at net.minecraft.class_761.method_22710(class_761.java:1375)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by Duzos** [comment]
OHhh shiit its because i clear the thing twice probably

**Comment by Duzos** [comment]
bc its only happening to people whove been rejoining multiple times

**Comment by Loqor** [comment]
Still an issue, randomly occurs

**Comment by Loqor** [comment]
its to do with the falling tardis renderer, because it cant get every element because of the dumb shit creativious did when it comes to rendering the model.
