### ISSUE TITLE
Crash because of animations on multiplayer

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#25]
`Cannot invoke "mdteam.ait.tardis.Tardis.getExterior()" because the return value of "mdteam.ait.core.blockentities.ExteriorBlockEntity.tardis()" is null
    at mdteam.ait.client.animation.ClassicAnimation.setupAnimation(ClassicAnimation.java:46) ~[ait-1.0.1-1.20.1-FABRIC.jar:?]
    at mdteam.ait.client.animation.ExteriorAnimation.lambda$new$0(ExteriorAnimation.java:36) ~[ait-1.0.1-1.20.1-FABRIC.jar:?]`
my guess: add a null check prolly fix it

**Comment by Duzos** [comment]
Similar: 
`The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "mdteam.ait.tardis.TardisDesktop.getCorners()" because the return value of "mdteam.ait.tardis.Tardis.getDesktop()" is null`
Likely just needs a resync

**Comment by Loqor** [comment]
Fixed a bit ago, but definitely now fixed due to the rewrite of the new markDirty() system.
