### ISSUE TITLE
Crashing in custom interior

### ISSUE THREAD

**Issue by ItsSky88** [amblelabs/ait#350]
When im pasting in my custom interior it keeps crashing me when i go a certain distance away from the centre console

I don't know if its a issue with ait or a problem with the fact im pasting in a build but heres the crash report

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-08-09 14:08:18
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "loqor.ait.tardis.Tardis.siege()" because the return value of "loqor.ait.tardis.link.v2.TardisRef.get()" is null
	at loqor.ait.core.blocks.DoorBlock.method_9530(DoorBlock.java:63)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032)
	at fi.dy.masa.litematica.util.RayTraceUtils.traceLoopSteps(RayTraceUtils.java:711)
	at fi.dy.masa.litematica.util.RayTraceUtils.rayTraceBlocks(RayTraceUtils.java:655)
	at fi.dy.masa.litematica.util.RayTraceUtils.getRayTraceFromEntity(RayTraceUtils.java:578)
	at fi.dy.masa.litematica.util.RayTraceUtils.getGenericTrace(RayTraceUtils.java:369)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderHoverInfo(OverlayRenderer.java:463)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:55)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:69)
	at net.minecraft.class_329.handler$cpc000$malilib$onGameOverlayPost(class_329.java:3876)
	at net.minecraft.class_329.method_1753(class_329.java:370)
	at net.minecraft.class_757.method_3192(class_757.java:926)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
	
	A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at loqor.ait.core.blocks.DoorBlock.method_9530(DoorBlock.java:63)
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1032)
	at fi.dy.masa.litematica.util.RayTraceUtils.traceLoopSteps(RayTraceUtils.java:711)
	at fi.dy.masa.litematica.util.RayTraceUtils.rayTraceBlocks(RayTraceUtils.java:655)
	at fi.dy.masa.litematica.util.RayTraceUtils.getRayTraceFromEntity(RayTraceUtils.java:578)
	at fi.dy.masa.litematica.util.RayTraceUtils.getGenericTrace(RayTraceUtils.java:369)
	at fi.dy.masa.litematica.render.OverlayRenderer.renderHoverInfo(OverlayRenderer.java:463)
	at fi.dy.masa.litematica.event.RenderHandler.onRenderGameOverlayPost(RenderHandler.java:55)
	at fi.dy.masa.malilib.event.RenderEventHandler.onRenderGameOverlayPost(RenderEventHandler.java:69)
	at net.minecraft.class_329.handler$cpc000$malilib$onGameOverlayPost(class_329.java:3876)
	at net.minecraft.class_329.method_1753(class_329.java:370)

-- Affected level --
Details:
	All players: 1 total; [class_746['its_sky_88'/69, l='ClientLevel', x=86282.53, y=7.58, z=43533.47]]
	Chunk stats: 1024, 609
	Level dimension: ait:tardis_dimension
	Level spawn location: World: (-160,60,-480), Section: (at 0,12,0 in -10,3,-30; chunk contains blocks -160,-64,-480 to -145,319,-465), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 2272564 game time, 611284 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, seasons:seasonal_lush_caves, Essential Assets, essential

**Comment by DrTheodor** [comment]
Oh, if youre pasting a custom interior make sure to NOT include a door or a console!
Doors, consoles, monitors and other blocks like this remember the tardis they were linked to

**Comment by ItsSky88** [comment]
ahhhh that makes sense thanks for the information lmao sorry for the time waste

**Comment by DrTheodor** [comment]
No worries, it's better to have this issue on github so we can point to it in future if someone has a similar problem
