### ISSUE TITLE
Crashes with Spice Of Life: Valheim

### ISSUE THREAD

**Issue by Aud999461** [amblelabs/ait#386]
Hello! I'd just like to report that Adventures In Time seems to crash with Spice Of Life: Valheim on startup. The crash report is pasted down below, sorry if its not too helpful I don't know how to really do crash reports on github-

`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-10-13 01:19:41
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'sol_valheim' at 'vice.sol_valheim.fabric.FabricInitializer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "loqor.ait.core.data.schema.SonicSchema.id()" because "loqor.ait.registry.impl.SonicRegistry.DEFAULT" is null
	at loqor.ait.core.item.SonicItem.method_7854(SonicItem.java:202)
	at vice.sol_valheim.ModConfig.getFoodConfig(ModConfig.java:29)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at vice.sol_valheim.SOLValheim.init(SOLValheim.java:65)
	at vice.sol_valheim.fabric.FabricInitializer.onInitialize(FabricInitializer.java:9)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
`

**Comment by Duzos** [comment]
bump

**Comment by Duzos** [comment]
add a nullcheck on `getDefaultStack`
