### ISSUE TITLE
Placing Down Console Block (Not Generator) Does Not Work

### ISSUE THREAD

**Issue by AuroraNyxs** [amblelabs/ait#408]
**Describe the bug**
Whenever placing down console block, It crashes the entire launcher.

**To Reproduce**
1. Grab the console from the creative menu
2. place down in tardis interior
3. Immeditaly crash

**Expected behavior**
Should place a hartnell console

**AIT Version:**
dev build #736 [ait-1.0.6.736-1.20.1-beta]

**Comment by Duzos** [comment]
please provide crash report

**Comment by JellyAurora** [comment]
Maaann Idk what im doin, I just made the account maan idk what im doing, do I just grab the uhhhh.. thing?

**Comment by Duzos** [comment]
just attach the crash report to a comment

**Comment by Duzos** [comment]
```
java.lang.ClassCastException: class net.minecraft.class_638 cannot be cast to class net.minecraft.class_3218 (net.minecraft.class_638 and net.minecraft.class_3218 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @271053e1)
	at loqor.ait.core.blocks.ConsoleBlock.method_9567(ConsoleBlock.java:106) ~[ait-1.0.6.736-1.20.1-beta.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41934(class_636.java:363) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41933(class_636.java:324) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1802) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2052) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[1.20.1-0.16.5.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.5.jar:?]
```

**Comment by Duzos** [comment]
In `ConsoleBlock` there is a cast to `ServerWorld` on line `106`, remove to fix.

**Comment by Loqor** [comment]
Works now, it was casting ServerWorld as you said.
