### ISSUE TITLE
Exterior door wont open if interior door doesnt exist

### ISSUE THREAD

**Issue by Addi3** [amblelabs/ait#415]
the beta server crashed and when i went back on some tardis doors wont open (other people tried and it wouldnt open still), but it plays the sound

**Comment by Duzos** [comment]
`java.lang.IllegalArgumentException: Cannot get property class_2758{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}`

**Comment by Duzos** [comment]
```
at loqor.ait.core.blocks.DoorBlock.lambda$static$0(DoorBlock.java:60) ~[ait-1.1.0.737-1.20.1-beta.jar:?]
        at loqor.ait.api.TardisEvents.lambda$static$24(TardisEvents.java:127) ~[ait-1.1.0.737-1.20.1-beta.jar:?]
        at loqor.ait.core.tardis.handler.DoorHandler.setDoorState(DoorHandler.java:197) ~[ait-1.1.0.737-1.20.1-beta.jar:?]
        at loqor.ait.core.tardis.handler.DoorHandler.useDoor(DoorHandler.java:344) ~[ait-1.1.0.737-1.20.1-beta.jar:?]
        at loqor.ait.core.blockentities.ExteriorBlockEntity.useOn(ExteriorBlockEntity.java:140) ~[ait-1.1.0.737-1.20.1-beta.jar:?]
        at loqor.ait.core.blocks.ExteriorBlock.method_9534(ExteriorBlock.java:320) ~[ait-1.1.0.737-1.20.1-beta.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[server-intermediary.jar:?]
```

**Comment by Loqor** [comment]
@Duzos they were trying to open doors from the fucked tardises placed in the previous version

**Comment by Duzos** [comment]
ah ok

**Comment by Addi3** [comment]
it just happened again, with a new tardis on the latest build (on the server)

**Comment by Duzos** [comment]
yup, console has same message

**Comment by Duzos** [comment]
i’d say just add a check that the door pos is actually a door in that lamba

**Comment by Duzos** [comment]
`DoorBlock` line `60`
