### ISSUE TITLE
Falling TARDIS Client -> Server cast crash

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#417]
Caused by: java.lang.ClassCastException: class loqor.ait.client.tardis.ClientTardis cannot be cast to class loqor.ait.core.tardis.ServerTardis (loqor.ait.client.tardis.ClientTardis and loqor.ait.core.tardis.ServerTardis are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @14bf9759)
    at loqor.ait.core.tardis.Tardis.asServer(Tardis.java:52) ~[ait-1.1.0.738-1.20.1-beta.jar:?]
    at loqor.ait.core.entities.FallingTardisEntity.stopFalling(FallingTardisEntity.java:149) ~[ait-1.1.0.738-1.20.1-beta.jar:?]
    at

add a client side check or smth

**Comment by Duzos** [comment]
in `FallingTardisEntity.stopFalling`

you could do `tardis instanceof ClientTardis` and return, or do some other way to check if its clientsided and return
