### ISSUE TITLE
ConcurrentModificationException with sendToSubscribers

### ISSUE THREAD

**Issue by duzos** [amblelabs/ait#5]
Not too sure why this is happening
According to google its when the map is getting edited while its being iterated over

**Comment by Suff99** [comment]
Show log where it's happening

**Comment by Duzos** [comment]
@Loqor pls send i dont have it rn

**Comment by Loqor** [comment]
[19:51:44] [Server thread/ERROR] (Minecraft) Failed to create block entity ait:door_block_entity_type
 java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:473) ~[guava-31.1-jre.jar:?]
	at mdteam.ait.tardis.ServerTardisManager.sendToSubscribers(ServerTardisManager.java:159) ~[main/:?]
	at mdteam.ait.tardis.wrapper.server.ServerTardisDesktop.setInteriorDoorPos(ServerTardisDesktop.java:19) ~[main/:?]
	at mdteam.ait.core.blockentities.DoorBlockEntity.setDesktop(DoorBlockEntity.java:165) ~[main/:?]
	at mdteam.ait.api.tardis.ILinkable.linkDesktop(ILinkable.java:32) ~[main/:?]
	at mdteam.ait.core.blockentities.DoorBlockEntity.setTardis(DoorBlockEntity.java:160) ~[main/:?]
	at mdteam.ait.core.blockentities.DoorBlockEntity.<init>(DoorBlockEntity.java:42) ~[main/:?]
	at net.minecraft.block.entity.BlockEntityType.instantiate(BlockEntityType.java:92) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.block.entity.BlockEntity.method_17899(BlockEntity.java:124) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.block.entity.BlockEntity.createFromNbt(BlockEntity.java:122) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.world.ChunkSerializer.method_39797(ChunkSerializer.java:408) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.world.chunk.WorldChunk.loadEntities(WorldChunk.java:442) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17227(ThreadedAnvilChunkStorage.java:751) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_20460(ThreadedAnvilChunkStorage.java:739) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem.java:62) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.executeTask(ServerChunkManager.java:564) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager.java:573) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:139) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.world.ServerChunkManager.getChunk(ServerChunkManager.java:140) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.world.World.getChunk(World.java:204) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.world.WorldView.getChunk(WorldView.java:156) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.world.World.getChunk(World.java:198) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.world.World.getChunk(World.java:77) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.world.WorldView.getChunk(WorldView.java:148) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at mdteam.ait.core.blockentities.ExteriorBlockEntity.onEntityCollision(ExteriorBlockEntity.java:170) ~[main/:?]
	at mdteam.ait.core.blocks.ExteriorBlock.onEntityCollision(ExteriorBlock.java:94) ~[main/:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.onEntityCollision(AbstractBlock.java:1121) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.entity.Entity.checkBlockCollision(Entity.java:1137) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.entity.Entity.tryCheckBlockCollision(Entity.java:851) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.entity.Entity.move(Entity.java:799) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerMove(ServerPlayNetworkHandler.java:962) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket.java:114) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$Full.apply(PlayerMoveC2SPacket.java:16) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:782) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:164) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:764) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:758) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:139) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:743) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:675) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-merged-project-root-1.20.1-net.fabricmc.yarn.1_20_1.1.20.1+build.10-v2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:51:44] [Server thread/WARN] (Minecraft) Skipping BlockEntity with id ait:door_block_entity_type

**Comment by Loqor** [comment]
the issue is with primarily the door block entity not properly loading its position in the interior (well, getting the tardis from its position in the dimension) before the other data of the tardis gets to it; ergo, the list error when trying to send the data to subscribers, and the block entity not loading properly. that is, my understanding of course anyway.

**Comment by Duzos** [comment]
Loqor — Today at 01:56
yk craig is gonna comment about the amount of sync methods right lol
duzo — Today at 01:56
yes

**Comment by Loqor** [comment]
apparently if you relog the issue is fine? what the- its nearly instant too

**Comment by Suff99** [comment]
If I had to fall about this coziness, I'd have a 67 hour long "Valve comments" video 

Anyways, I've only glanced at this code on my phone where the error is - looks like you don't use the iterator and use for and etc but the list is also cleared by other code 

You need to use a iterator and constantly check if you have another value 

Imagine it like a warehouse manager and a drivers, warehouse manager with a brain aneurism has been told there's 6 busses and he needs to wash them all but the drivers keep blowing up their busses and the warehouse worker has no idea what to do because he really wants 6 busses but they're all blown up

**Comment by Duzos** [comment]
lmao
i think i understand
so i just add a `.iterator()` 
making it be like
`for (Iterator<ServerPlayerEntity> it = this.subscribers.get(tardis.getUuid()).iterator(); it.hasNext(); )` ?

**Comment by Loqor** [comment]
> lmao i think i understand so i just add a `.iterator()` making it be like `for (Iterator<ServerPlayerEntity> it = this.subscribers.get(tardis.getUuid()).iterator(); it.hasNext(); )` ?

i tried that already, but i was also loading the chunk at the same time; could work though.

**Comment by Duzos** [comment]
was doing something that produced the error
changed the line of code to that new line and then reloaded
redid the thing causing the error and it all worked fine
pretty sure its fixed!
thank you so much craig <33

**Comment by Duzos** [comment]
yeah it broke again
but its working more frequently than before so its not as bad
too be honest im too tired to fix this rn so ill look at it properly later

the error:

[02:13:30] [Server thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket@3c926806, suppressing error
 java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at com.google.common.collect.AbstractMapBasedMultimap$Itr.next(AbstractMapBasedMultimap.java:1202) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.AbstractMultimap.putAll(AbstractMultimap.java:99) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ArrayListMultimap.putAll(ArrayListMultimap.java:61) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ArrayListMultimap.<init>(ArrayListMultimap.java:127) ~[guava-31.1-jre.jar:?]
	at com.google.common.collect.ArrayListMultimap.create(ArrayListMultimap.java:108) ~[guava-31.1-jre.jar:?]
	at mdteam.ait.tardis.ServerTardisManager.sendToSubscribers(ServerTardisManager.java:161) ~[main/:?]

**Comment by Duzos** [comment]
everything hurts
so the problems grown and now you cant do anything without this error showing
basically its because of what craig said earlier
but the solution i think is to create a DEEEPy copy of the multimap OR ensure that nothing will happen to it while we're iterating through it
both ways are too much for me right now.

**Comment by Duzos** [comment]
deep copy will also be like really slow so thats not good
but i also dont want to crack down on the millions of sync methods rn

**Comment by Duzos** [comment]
temporarily solved with that commit, will likely be reopened because of how bad it is but its 4am and idc
exterior doors are now no longer synced properly too!
fucking hate coding :(

**Comment by Duzos** [comment]
the gson got removed and replaced with `markDirty` but this happens sometimes

**Comment by Loqor** [comment]
[16:16:08] [Server thread/ERROR]:
 Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:?]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:?]
	at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:473) ~[guava-31.1-jre.jar:?]
	at mdteam.ait.tardis.wrapper.server.manager.ServerTardisManager.sendToSubscribers(ServerTardisManager.java:176) ~[ait-1.0.1-1.20.1.jar:?]
	at mdteam.ait.tardis.wrapper.server.ServerTardis.sync(ServerTardis.java:27) ~[ait-1.0.1-1.20.1.jar:?]
	at mdteam.ait.tardis.Tardis.startTick(Tardis.java:142) ~[ait-1.0.1-1.20.1.jar:?]
	at mdteam.ait.tardis.wrapper.server.manager.ServerTardisManager.lambda$new$6(ServerTardisManager.java:96) ~[ait-1.0.1-1.20.1.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$0(ServerTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.2.2+b3afc78b77-3792d0d4b63e847b.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zfa000$fabric-lifecycle-events-v1$onStartTick(MinecraftServer.java:2857) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
	
	this is the error i've gotten

**Comment by Duzos** [comment]
_**```threading```**_

**Comment by Duzos** [comment]
Don't say another Goddamn word. Up until now, I've been polite. If you say ANYTHING else - ONE word - I will kill myself. And when my tainted spirit finds its destination, I will topple the Master of that dark place. From my black throne, I will lash together a machine of bone and blood, and fueled by my hatred for you this Fear Engine will bore a hole between this world and that one. When it begins, you will hear the sound of children screaming -as though from a great distance. A smoking orb of NOTHING will grow above your bed, and from it will emerge a thousand starving crows. As I slip through the widening maw in my new form, you will catch only a glimpse of my radiance before you are incinerated. Then, as tears of bubbling pitch stream down my face, my dark world will begin. I will open one of my six mouths, and I will sing the song that ends the Earth.

**Comment by Suff99** [comment]
![F7q2t5lXAAAmCE8](https://github.com/M-D-Team/ait-fabric-1.20.1/assets/36424503/71942258-1f00-4fb2-ab8f-dad37b4a629e)

**Comment by Duzos** [comment]
he fix c5b79754b5b9134ef3dbd9817b747581b22650c4
