### ISSUE TITLE
engine is a bit allergic to iron (crash upon rightclicking engine with iron)

### ISSUE THREAD

**Issue by Saturnorsomthing** [amblelabs/ait#615]
[latest.log](https://github.com/user-attachments/files/17908899/latest.log)

**Comment by Duzos** [comment]
```
java.lang.ClassCastException: class loqor.ait.client.tardis.ClientTardis cannot be cast to class loqor.ait.core.tardis.ServerTardis (loqor.ait.client.tardis.ClientTardis and loqor.ait.core.tardis.ServerTardis are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @598067a5)
	at loqor.ait.core.tardis.Tardis.asServer(Tardis.java:53) ~[ait-1.2.0.920-1.20.1-beta_engine.jar:?]
	at loqor.ait.core.tardis.TardisDesktop.lambda$playSoundAtEveryConsole$2(TardisDesktop.java:152) ~[ait-1.2.0.920-1.20.1-beta_engine.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at loqor.ait.core.tardis.TardisDesktop.playSoundAtEveryConsole(TardisDesktop.java:152) ~[ait-1.2.0.920-1.20.1-beta_engine.jar:?]
	at loqor.ait.core.tardis.handler.SubSystemHandler.enablePower(SubSystemHandler.java:178) ~[ait-1.2.0.920-1.20.1-beta_engine.jar:?]```
