### ISSUE TITLE
Crash with sonic

### ISSUE THREAD

**Issue by Kirbeeey** [amblelabs/ait#796]
**Describe the bug**
The Generalized Subsystem core block crashes when viewed with the sonic screwdriver

**To Reproduce**
1. Place the The Generalized Subsystem
2. And look him with the sonic screwdriver
3. Crash in game and crash the server when you play in multiplayer and player can't log to the server and you must reset the world when you crash 
4. [crash-2024-12-20_19.10.39-client.txt](https://github.com/user-attachments/files/18214036/crash-2024-12-20_19.10.39-client.txt)

**AIT Version:**
ait-1.2.0.1101-1.20.1-beta

**Comment by Kirbe-ctrl** [comment]
[14:35:12] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "loqor.ait.core.engine.SubSystem.isEnabled()" because "system" is null
	at loqor.ait.client.renderers.SonicRendering.renderDurability(SonicRendering.java:181) ~[ait-1.2.0.1120-1.20.1-beta.jar:?]
	at loqor.ait.client.renderers.SonicRendering.renderGui(SonicRendering.java:156) ~[ait-1.2.0.1120-1.20.1-beta.jar:?]
	at loqor.ait.client.AITModClient.lambda$onInitializeClient$17(AITModClient.java:235) ~[ait-1.2.0.1120-1.20.1-beta.jar:?]
	at net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:27) ~[fabric-rendering-v1-3.0.8+1802ada577-bbcf8e89e2242cd8.jar:?]
	at net.minecraft.class_329.handler$zll000$fabric-rendering-v1$render(class_329.java:1886) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:370) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:926) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
if you want i have re crash with his bug but i solo this time

**Comment by Loqor** [comment]
fixc

**Comment by Kirbe-ctrl** [comment]
nice thanks
