### ISSUE TITLE
possible multi dimension breaking /  Signature is missing from Property textures

### ISSUE THREAD

**Issue by trerrturyy** [amblelabs/ait#836]
![image](https://github.com/user-attachments/assets/64afc393-85f2-4311-9bbd-f60b27e9dac6)
 i dont know how to replicate this bug it just started happening

when i place down a tardis or when i grow a coral to max when the game tries to create a tardis dimention it completely breaks and it says something about tick speed

![image](https://github.com/user-attachments/assets/5188ed44-ff2f-490d-a206-1b3301f2be77)

im sure this bug is about multi dimension and it breaking. i created a new modrinth profile and the bug came with it i dont know if its another mod or just ait (yes i used the same mods but they all worked fine before)

**Comment by trerrturyy** [comment]
![image](https://github.com/user-attachments/assets/967359b5-3403-435a-9271-c9507be4f52f)
it also keeps saying diff versions of this but its about the same everytime

here is a link to the entire log https://mclo.gs/M2lKQk9

**Comment by trerrturyy** [comment]
should also say this isnt a beta its 1.1.0 or sum

the lastest release

**Comment by DrTheodor** [comment]
> Signature is missing from Property textures
I don't think it's an AIT bug..? This error messsage is getting printed before tardis dimension creation in the logs.

The other thingy is perfomance problems. Creating a new dimension, pasting the interior and doing the initialization takes time.

**Comment by trerrturyy** [comment]
i swear the errrors are after the tardis dimension tries to get created?

**Comment by DrTheodor** [comment]
![image](https://github.com/user-attachments/assets/26b3a3bc-9398-4dd4-b17c-e353924f275b)

**Comment by DrTheodor** [comment]
For whoever (probably me) who's gonna solve the perfomance problems:
```
	at knot//com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:222)
	at knot//net.minecraft.class_2158$class_2160.method_36318(class_2158.java:96)
	at knot//net.minecraft.class_2158$class_2160.method_9198(class_2158.java:90)
	at knot//net.minecraft.class_2991$class_2992.method_12914(class_2991.java:135)
	at knot//net.minecraft.class_2991$class_6345.method_36346(class_2991.java:210)
	at knot//net.minecraft.class_2991.method_36341(class_2991.java:85)
	at knot//net.minecraft.class_2991.method_12904(class_2991.java:69)
	at knot//net.minecraft.class_231.method_17938(class_231.java:18)
	at knot//net.minecraft.class_231$$Lambda$22259/0x0000024b886d06b0.accept(Unknown Source)
	at java.base@17.0.13/java.util.Optional.ifPresent(Unknown Source)
	at knot//net.minecraft.class_231.method_967(class_231.java:18)
	at knot//net.minecraft.class_231.method_974(class_231.java:8)
	at knot//net.minecraft.class_236.method_988(class_236.java:84)
	at knot//net.minecraft.class_3218.method_29203(class_3218.java:409)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:317)
	at knot//dev.pavatus.multidim.MultiDim.add(MultiDim.java:103)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.create(TardisDimension.java:43)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.create(TardisDimension.java:49)
```

```
	at knot//com.mojang.brigadier.context.CommandContextBuilder.build(CommandContextBuilder.java:107)
	at knot//com.mojang.brigadier.context.CommandContextBuilder.build(CommandContextBuilder.java:107)
	at knot//com.mojang.brigadier.context.CommandContextBuilder.build(CommandContextBuilder.java:107)
	at knot//com.mojang.brigadier.context.CommandContextBuilder.build(CommandContextBuilder.java:107)
	at knot//com.mojang.brigadier.context.CommandContextBuilder.build(CommandContextBuilder.java:107)
	at knot//com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:222)
	at knot//net.minecraft.class_2158$class_2160.method_36318(class_2158.java:96)
	at knot//net.minecraft.class_2158$class_2160.method_9198(class_2158.java:90)
	at knot//net.minecraft.class_2991$class_2992.method_12914(class_2991.java:135)
	at knot//net.minecraft.class_2991$class_6345.method_36346(class_2991.java:210)
	at knot//net.minecraft.class_2991.method_36341(class_2991.java:85)
	at knot//net.minecraft.class_2991.method_12904(class_2991.java:69)
	at knot//net.minecraft.class_231.method_17938(class_231.java:18)
	at knot//net.minecraft.class_231$$Lambda$22259/0x0000024b886d06b0.accept(Unknown Source)
	at java.base@17.0.13/java.util.Optional.ifPresent(Unknown Source)
	at knot//net.minecraft.class_231.method_967(class_231.java:18)
	at knot//net.minecraft.class_231.method_974(class_231.java:8)
	at knot//net.minecraft.class_236.method_988(class_236.java:84)
	at knot//net.minecraft.class_3218.method_29203(class_3218.java:409)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:317)
	at knot//dev.pavatus.multidim.MultiDim.add(MultiDim.java:103)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.create(TardisDimension.java:43)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.create(TardisDimension.java:49)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.lambda$getOrCreate$0(TardisDimension.java:60)
	at knot//loqor.ait.core.tardis.dim.TardisDimension$$Lambda$23053/0x0000024b887e8000.get(Unknown Source)
	at java.base@17.0.13/java.util.Optional.orElseGet(Unknown Source)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.getOrCreate(TardisDimension.java:60)
	at knot//loqor.ait.core.tardis.ServerTardis.getInteriorWorld(ServerTardis.java:81)
	at knot//loqor.ait.core.tardis.TardisDesktop.changeInterior(TardisDesktop.java:105)
	at knot//loqor.ait.core.tardis.TardisDesktop.onCreate(TardisDesktop.java:64)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:15)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:6)
	at knot//loqor.ait.api.TardisComponent.init(TardisComponent.java:95)
	at knot//loqor.ait.core.tardis.Tardis.onInit(Tardis.java:38)
	at knot//loqor.ait.core.tardis.Tardis.onInit(Tardis.java:19)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:18)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:6)
	at knot//loqor.ait.core.tardis.Tardis.init(Tardis.java:44)
	at knot//loqor.ait.core.tardis.manager.TardisBuilder.build(TardisBuilder.java:92)
	at knot//loqor.ait.core.tardis.manager.old.DeprecatedServerTardisManager.create(DeprecatedServerTardisManager.java:74)
	at knot//loqor.ait.core.tardis.manager.ServerTardisManager.create(ServerTardisManager.java:88)
	at knot//loqor.ait.core.blocks.CoralPlantBlock.createTardis(CoralPlantBlock.java:109)
	at knot//loqor.ait.core.blocks.CoralPlantBlock.method_9514(CoralPlantBlock.java:97)
```

```
	at knot//net.minecraft.class_2168.method_51411(class_2168.java:199)
	at knot//net.minecraft.class_2991$class_6345.method_51275(class_2991.java:192)
	at knot//net.minecraft.class_2991$class_6345.method_36343(class_2991.java:181)
	at knot//net.minecraft.class_2991.method_36341(class_2991.java:79)
	at knot//net.minecraft.class_2991.method_12904(class_2991.java:69)
	at knot//net.minecraft.class_3062.method_13381(class_3062.java:46)
	at knot//net.minecraft.class_3062.method_13383(class_3062.java:35)
	at knot//net.minecraft.class_3062$$Lambda$17436/0x0000024b8808aae0.run(Unknown Source)
	at knot//com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
	at knot//net.minecraft.class_2158$class_2160.method_36318(class_2158.java:96)
	at knot//net.minecraft.class_2158$class_2160.method_9198(class_2158.java:90)
	at knot//net.minecraft.class_2991$class_2992.method_12914(class_2991.java:135)
	at knot//net.minecraft.class_2991$class_6345.method_36346(class_2991.java:210)
	at knot//net.minecraft.class_2991.method_36341(class_2991.java:85)
	at knot//net.minecraft.class_2991.method_12904(class_2991.java:69)
	at knot//net.minecraft.class_231.method_17938(class_231.java:18)
	at knot//net.minecraft.class_231$$Lambda$22259/0x0000024b886d06b0.accept(Unknown Source)
	at java.base@17.0.13/java.util.Optional.ifPresent(Unknown Source)
	at knot//net.minecraft.class_231.method_967(class_231.java:18)
	at knot//net.minecraft.class_231.method_974(class_231.java:8)
	at knot//net.minecraft.class_236.method_988(class_236.java:84)
	at knot//net.minecraft.class_3218.method_29203(class_3218.java:409)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:317)
	at knot//dev.pavatus.multidim.MultiDim.add(MultiDim.java:103)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.create(TardisDimension.java:43)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.create(TardisDimension.java:49)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.lambda$getOrCreate$0(TardisDimension.java:60)
	at knot//loqor.ait.core.tardis.dim.TardisDimension$$Lambda$23053/0x0000024b887e8000.get(Unknown Source)
	at java.base@17.0.13/java.util.Optional.orElseGet(Unknown Source)
	at knot//loqor.ait.core.tardis.dim.TardisDimension.getOrCreate(TardisDimension.java:60)
	at knot//loqor.ait.core.tardis.ServerTardis.getInteriorWorld(ServerTardis.java:81)
	at knot//loqor.ait.core.tardis.TardisDesktop.changeInterior(TardisDesktop.java:105)
	at knot//loqor.ait.core.tardis.TardisDesktop.onCreate(TardisDesktop.java:64)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:15)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:6)
	at knot//loqor.ait.api.TardisComponent.init(TardisComponent.java:95)
	at knot//loqor.ait.core.tardis.Tardis.onInit(Tardis.java:38)
	at knot//loqor.ait.core.tardis.Tardis.onInit(Tardis.java:19)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:18)
	at knot//loqor.ait.api.Initializable.init(Initializable.java:6)
	at knot//loqor.ait.core.tardis.Tardis.init(Tardis.java:44)
	at knot//loqor.ait.core.tardis.manager.TardisBuilder.build(TardisBuilder.java:92)
	at knot//loqor.ait.core.tardis.manager.old.DeprecatedServerTardisManager.create(DeprecatedServerTardisManager.java:74)
	at knot//loqor.ait.core.tardis.manager.ServerTardisManager.create(ServerTardisManager.java:88)
	at knot//loqor.ait.core.blocks.CoralPlantBlock.createTardis(CoralPlantBlock.java:109)
	at knot//loqor.ait.core.blocks.CoralPlantBlock.method_9514(CoralPlantBlock.java:97)
```

**Comment by DrTheodor** [comment]
As far as i see, multidim needs an optimization

**Comment by trerrturyy** [comment]
alr

**Comment by Saturnorsomthing** [comment]
just gonna assigne theo as hes the preformance magic person
